# Site settings
title: "Visualization in Data Science (VDS at IEEE VIS)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at IEEE VIS 2023)"
baseurl: "/2023"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2023"
conferencedate: "TBD" 

deadline_submission_vis:  "Thur., <s>July 14th</s>, 2023, 5:00 pm PDT"
deadline_notification_vis: "Thur., <s>August 25th</s>, 2023, 5:00 pm PDT"
event2_date: "October 16"

# Build settings
markdown: kramdown

collections:
- talks

